# Generated by Django 4.0.3 on 2022-04-05 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cumtomer',
            new_name='Customer',
        ),
    ]
